# ubuntu terminal alias
alias c='clear'
alias apt-get='sudo apt-get'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get update && sudo apt-get upgrade'
alias install='sudo apt-get install'
alias shut00='sudo shutdown -h 00:00'
alias ..='cd ..'
alias h='history'

# git alias
alias got='git '
alias get='git '
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend -m'
alias gd='git diff'
alias go='git checkout'
alias gps='git push'
alias gpl='git pull'
alias gl='git log --pretty=format:'\''%h %ad | %s%d [%an]'\'' --graph --date=short'
alias gha='git hist --all'
alias gpso='git push -u origin'
alias gps='git push -u'
alias gpl='git pull -u'
